spring.application.name=worknest

spring.datasource.url=jdbc:mysql://localhost:3306/worknest_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mrudula@10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false



